import { Config, Log } from "@/providers/Data/context";
import { BusinessType, Page, Player, Warehouse } from "@/types/index.type";
import { debugData } from "@/utils/debugData";

debugData([
  { action: "ui:setPage", data: "business" as Page },
  {
    action: "ui:setupUI",
    data: {
      setLocale: {
        on: "On",
        close: "Close",
        setup: "Setup",
        machine_level: "Machine Level",
        working: "Operational",
        outcome: "Output",
        info: "Details",
        money_inside: "Funds Available",
        up: "Upgrade",
        modal_upgrade_money_washing_title: "Upgrade Money Laundering",
        modal_money_washing_desc:
          "Upgrade the money laundering section to level {{level}} in your warehouse.",
        deposit: "Deposit",
        upgrade_raw_materials_stock: "Increase Raw Material Storage",
        desc_upgrade_raw_materials_stock:
          "Expand your raw material storage capacity.",
        modal_theme_update_desc:
          "You’re about to switch to the {{theme}} theme. Changing themes will destroy all produced packages. Are you sure?",
        withdraw: "Withdraw",
        business_management: "Business Management",
        manage_business: "Manage Your Business",
        warehouse_name: "Warehouse Name",
        employee_list: "Employee List",
        manager_detail: "Manager Details",
        identifier: "ID",
        name: "Name",
        remove: "Remove",
        double_click_remove: "Double-click to remove",
        business_owner: "Business Owner",
        business_manager: "Business Manager",
        owner: "Owner",
        manager: "Manager",
        blip: "Map Marker",
        update_blip: "Change Marker Color",
        invite_manager: "Invite Manager",
        desc_invite_manager: "Add new managers to your business.",
        manager_list: "Manager List",
        player_source_id: "Player ID",
        invite: "Send Invite",
        business: "Business",
        level: "Level",
        exp: "Experience",
        raw_materials_and_drug_sale: "Raw Materials & Sales",
        desc_raw_materials_and_drug_sale:
          "Starting a business in our city requires raw materials, crucial for growth. Be cautious of the police when selling.",
        sale_mission: "Sale Mission",
        start_collection: "Begin Collection",
        ok: "OK",
        change_business_theme: "Change Business Theme",
        selected: "Selected",
        buy: "Purchase",
        money_type: "$",
        management_menu: "Management Menu",
        business_name: "Business Name",
        information: "Information",
        toggle_blip_visible: "Toggle Map Marker",
        working_info: "Production Details",
        desc_working_info:
          "Ensure your resources are stocked and you have enough workers before starting production. More workers increase production speed and capacity.",
        start_working: "Start Production",
        stop_working: "Stop Production",
        black_money_washing: "Money Laundering",
        purchase: "Buy",
        desc_buy_any: "You are about to purchase this item. Do you confirm?",
        cancel: "Cancel",
        confirm: "Confirm",
        current_progress_skill: "Skill Progress",
        production_time_left: "Minutes until production completes",
        progress: "Progress",
        you_will_earn: "You will earn",
        products: "Products",
        piece: "Unit",
        packaged_product: "Packaged Product",
        lab_type: "Lab Type",
        total_employees: "Total Employees",
        employees: "Employees",
        created_at: "Created On",
        stock: "Stock",
        water: "Water",
        gas: "Gas",
        power: "Power",
        electricity: "Electricity",
        raw_materials: "Raw Materials",
        management_panel: "Management Panel",
        desc_management_panel: "Adjust your business settings.",
        recruit_employee: "Hire Employee",
        desc_recruit_employee: "Manage your workforce.",
        pay: "Pay",
        change: "Modify",
        upgrade_vehicle: "Upgrade Vehicle",
        desc_upgrade_vehicle:
          "Upgrade your vehicle to carry more raw materials.",
        purchase_storage: "Expand Storage",
        desc_purchase_storage: "Increase your storage capacity.",
        hide_map_blip: "Hide Map Marker",
        desc_hide_map_blip: "Show or hide the map marker.",
        open: "Open",
        security_system: "Security System",
        desc_security_system:
          "Install security systems and cameras to prevent theft.",
        interior_light: "Interior Lighting",
        desc_interior_light: "Turn the warehouse lights on or off.",
        transfer_company: "Transfer Business",
        desc_transfer_company:
          "Enter the ID of the person to transfer ownership to.",
        terminate_contract: "Cancel Contract",
        desc_terminate_contract: "End your business contract.",
        delete: "Delete",
        confirm_action: "Are you sure?",
        modal_terminate_warehouse_desc:
          "This warehouse will no longer belong to you.",
        security_camera: "Security Camera",
        desc_security_camera: "Monitor the exterior of your warehouse.",
        double_click_transfer: "Double-click to transfer",
        safe_actions: "Safe Operations",
        desc_safe_actions: "Keep your funds secure here.",
        info_safe_actions:
          "Deposit both dirty and clean money into the safe. Clean money is required for salaries and resources. Production cannot start without sufficient clean money.",
        open_safe: "Access Safe",
        dirty_money: "Dirty Money",
        clean_money: "Clean Money",
        modal_buy_security_desc: "Purchase a security system.",
        enter_amount: "Enter Amount",
        select_item: "Select Item",
        total_price: "Total Cost",
        modal_payment_employee_title: "Pay Employees",
        modal_payment_employee_desc: "Do you agree to pay employee salaries?",
        modal_noneed_title: "Not Required",
        modal_noneed_desc: "This action isn’t necessary right now.",
        recruit_employees: "Hire Employees",
        desc_recruit_employees:
          "Hiring more employees boosts production speed and output, but increases costs.",
        dismiss_employees: "Dismiss Employees",
        desc_dismiss_employees: "Remove existing workers.",
        modal_upgrade_vehicle_title: "Upgrade Vehicle",
        modal_upgrade_vehicle_desc:
          "Current level: {{1}}. Upgrading your vehicle increases its capacity to {{2}} packages.",
        modal_upgrade_raw_materials_stock_title: "Expand Storage",
        modal_upgrade_raw_materials_stock_desc:
          "Current level: {{1}}. Upgrade to increase storage capacity to {{2}}.",
        upgrade: "Upgrade",
        modal_upgrade_interior_title: "Upgrade Interior",
        modal_upgrade_interior_desc:
          "Current level: {{1}}. Upgrade your interior to unlock production with necessary equipment.",
        upgrade_interior: "Enhance Interior",
        desc_upgrade_interior: "Improve your warehouse interior.",
        almost_ready: "Almost ready...",
        warehouse_safe: "Warehouse Safe",
      },
      setConfig: {
        BusinessTypes: [
          { key: "weed", label: "Weed", requiredLevel: 1, price: 50000 },
          {
            key: "cocaine",
            label: "Cocaine",
            requiredLevel: 10,
            price: 100000,
          },
          { key: "meth", label: "Meth", requiredLevel: 20, price: 200000 },
        ] as BusinessType[],
        SecuritySystemPrice: 5000,
        Stock: {
          ["water"]: { unit_price: 0.35 },
          ["gas"]: { unit_price: 0.35 },
          ["electricity"]: { unit_price: 0.35 },
        },
        InventoryImagesFolder: "",
        Employee: {
          recruitment_fee: 5000,
          salary_fee: 500,
        },
        VehicleUpgrades: {
          [1]: { maxPackageCount: 5 },
          [2]: { price: 50000, maxPackageCount: 10 },
        } as any,
        RawMaterialStockUpgrades: {
          [1]: { price: 50000, maxStockCount: 200 },
          [2]: { price: 50000, maxStockCount: 300 },
          [3]: { price: 50000, maxStockCount: 400 },
          [4]: { price: 50000, maxStockCount: 500 },
        } as any,
        MoneyWashingUpgrades: {
          [1]: { price: 50000, productionPerMin: 1000 },
          [2]: { price: 50000, productionPerMin: 2000 },
          [3]: { price: 50000, productionPerMin: 3000 },
          [4]: { price: 50000, productionPerMin: 5000 },
        } as any,
      } as Config,
      setPlayer: {
        name: "Romario Richardson",
        identifier: "five:123",
      } as Player,
    },
  },
  // { action: "ui:setAlert", data: { text: "Test alert", type: "error" } },
  {
    action: "ui:setCurrentWarehouse",
    data: {
      id: 1,
      warehouse_index: 1,
      business_theme: "weed",
      experience: 500000,
      level: 27,
      name: "0Resmon Company",
      owner_id: "ali",
      nextLeveLExp: 600000,
      managers: [
        { identifier: "ali", name: "Romario Richardson", owner: true },
        { identifier: "five:123", name: "Romario Richardson", owner: false },
      ],
      production_time: 724.96551724138,
      production_count: 60,
      meta: {
        max_package_stock: 200,
        max_raw_materials_stock: 200,
        security_system: false,
        interior_light: true,
        blip_hidden: false,
        rm_task_vehicle_level: 1,
        interior_level: 1,
        is_working: true,
        last_working_at: Math.floor(Date.now() / 1000),
        raw_materials_stock_level: 1,
        money_washing_level: 0,
      },
      packaged_product_stock: 120,
      raw_materials_stock: 100,
      electricity_stock: 600,
      gas_stock: 450,
      water_stock: 300,
      employee_count: 9,
      dirty_money: 3567,
      clean_money: 108000,
      created_at: Date.now(),
      last_processed: undefined,
    } as Warehouse,
  },
  {
    action: "ui:setBuyWarehouse",
    data: {
      price: 50000,
      label: "Test Warehouse",
      key: 1,
    },
  },
  {
    action: "ui:setLogs",
    data: [
      { log_message: "Test message", created_at: new Date().toLocaleString() },
      { log_message: "Test message", created_at: new Date().toLocaleString() },
      {
        log_message:
          "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
        created_at: new Date().toLocaleString(),
      },
      { log_message: "Test message", created_at: new Date().toLocaleString() },
    ] as Log[],
  },
] as never);
