INSERT INTO `houses_furniture_list` (`model`, `label`, `price`, `deliverySize`, `tag`, `isOutdoor`, `isIndoor`, `interactableName`, `metadata`) VALUES
	('apa_mp_h_acc_rugwooll_03', 'Wool Rug', 450, 2, 'decorations', 0, 1, NULL, NULL),
	('apa_mp_h_bed_chestdrawer_02', 'Modern Chest of Drawers (Dark)', 7800, 3, 'storage', 0, 1, 'storage', '{"slots":10,"weight":10000}'),
	('apa_mp_h_bed_double_09', 'Double Bed (Black Upholstered)', 3800, 3, 'bed', 0, 1, NULL, NULL),
	('apa_mp_h_bed_wide_05', 'Wide Bed (Red Frame)', 2800, 3, 'bed', 0, 1, NULL, NULL),
	('apa_mp_h_bed_with_table_02', 'Double Bed with Built-in Table', 4500, 3, 'bed', 0, 1, NULL, NULL),
	('apa_mp_h_din_table_01', 'Glass Dining Table', 7000, 3, 'table', 1, 1, NULL, NULL),
	('apa_mp_h_stn_chairarm_01', 'Modern Armchair (Mustard)', 2000, 2, 'chair', 0, 1, NULL, NULL),
	('apa_mp_h_stn_chairstrip_03', 'Armchair (Red Fabric)', 2000, 3, 'chair', 0, 1, NULL, NULL),
	('apa_mp_h_stn_chairstrip_08', 'Armchair (Cyan Fabric)', 2000, 3, 'chair', 0, 1, NULL, NULL),
	('apa_mp_h_stn_sofacorn_01', 'Corner Sofa (L-Shaped, Cream)', 4950, 3, 'sofa', 1, 1, NULL, NULL),
	('apa_mp_h_stn_sofacorn_08', 'Corner Sofa (Beige, Cushioned)', 4400, 3, 'sofa', 0, 1, NULL, NULL),
	('apa_mp_h_stn_sofacorn_09', 'Corner Sofa (Dark, Modern)', 5500, 3, 'sofa', 0, 1, NULL, NULL),
	('apa_mp_h_str_shelffloorm_02', 'Floor Standing Shelf (Wood & Black)', 8000, 3, 'storage', 0, 1, 'storage', '{"slots":10,"weight":10000}'),
	('apa_mp_h_str_sideboardl_11', 'Low Sideboard (Dark Wood)', 10000, 3, 'storage', 0, 1, 'storage', '{"slots":10,"weight":10000}'),
	('apa_mp_h_str_sideboardl_13', 'Low Sideboard (White & Gray)', 12000, 3, 'storage', 0, 1, 'storage', '{"slots":10,"weight":10000}'),
	('apa_mp_h_str_sideboardl_14', 'Low Sideboard (White & Wood)', 11500, 3, 'storage', 0, 1, 'storage', '{"slots":10,"weight":10000}'),
	('apa_mp_h_tab_sidelrg_02', 'Modern Curved Chaise Lounger', 3500, 2, 'table', 1, 1, NULL, NULL),
	('bkr_prop_biker_chairstrip_01', 'Leather Club Armchair (Brown)', 650, 3, 'chair', 1, 1, NULL, NULL),
	('bkr_prop_biker_garage_locker_01', 'Open Biker Locker', 4200, 3, 'storage', 1, 1, 'wardrobe', NULL),
	('bkr_prop_gunlocker_01a', 'Gun Locker Cabinet', 9200, 3, 'storage', 1, 1, 'storage', '{"slots":10,"weight":10000}'),
	('ex_mp_h_off_sofa_003', 'Executive Sofa (Charcoal)', 3200, 3, 'sofa', 0, 1, NULL, NULL),
	('ex_mp_h_off_sofa_02', 'Executive Sofa (Gray)', 3200, 3, 'sofa', 1, 1, NULL, NULL),
	('ex_prop_exec_bed_01', 'Executive Bed (Beige Upholstery)', 1100, 3, 'bed', 0, 1, NULL, NULL),
	('gr_prop_gr_rsply_crate04a', 'Green Crate', 7200, 3, 'storage', 1, 1, 'storage', '{"weight":15000,"slots":8}'),
	('h4_mp_h_yacht_sofa_01', 'Yacht Sofa (White & Brown)', 7500, 3, 'sofa', 0, 1, NULL, NULL),
	('h4_mp_h_yacht_strip_chair_01', 'Yacht Lounge Chair (White)', 1400, 3, 'chair', 1, 1, NULL, NULL),
	('h4_prop_h4_glass_disp_01a', 'Glass Display Pedestal', 1000, 2, 'decorations', 1, 1, NULL, NULL),
	('hei_heist_bed_double_08', 'Modern Double Bed (Dark Gray)', 3700, 3, 'bed', 0, 1, NULL, NULL),
	('hei_heist_din_chair_02', 'Dining Chair (Red Plastic)', 350, 2, 'chair', 1, 1, NULL, NULL),
	('hei_heist_stn_sofacorn_05', 'Corner Sofa (Dark Blue)', 3900, 3, 'sofa', 0, 1, NULL, NULL),
	('hei_heist_stn_sofacorn_06', 'Corner Sofa (Green Cushions)', 3700, 3, 'sofa', 0, 1, NULL, NULL),
	('hei_prop_yah_lounger', 'Rattan Lounger (Dark Frame)', 600, 3, 'chair', 1, 1, NULL, NULL),
	('hei_prop_yah_seat_01', 'Rattan Chair (Single, Narrow)', 650, 2, 'chair', 1, 1, NULL, NULL),
	('hei_prop_yah_seat_02', 'Rattan Chair (Wide Seat)', 800, 2, 'chair', 1, 1, NULL, NULL),
	('hei_prop_yah_seat_03', 'Rattan Chair (Armrests)', 950, 3, 'chair', 1, 1, NULL, NULL),
	('hei_prop_yah_table_01', 'Yacht Dining Table (Wooden)', 500, 1, 'table', 1, 1, NULL, NULL),
	('hei_prop_yah_table_02', 'Yacht Table (With Cloth)', 550, 2, 'table', 1, 1, NULL, NULL),
	('hei_prop_yah_table_03', 'Yacht Table (Blue Legs)', 1000, 3, 'table', 1, 1, NULL, NULL),
	('m23_2_prop_m32_weaponcrate_01a', 'Weapon Wooden Crate', 6800, 2, 'storage', 1, 1, 'storage', '{"weight":8000,"slots":7}'),
	('prop_airhockey_01', 'Air Hockey Table', 0, 3, 'recreation', 1, 1, NULL, NULL),
	('prop_amp_01', 'Guitar Amplifier', 1200, 1, 'electronic', 1, 1, NULL, NULL),
	('prop_armchair_01', 'Upholstered Armchair (Brown Fabric)', 650, 2, 'chair', 0, 1, NULL, NULL),
	('prop_barbell_01', 'Dumbbell 30kg', 180, 1, 'recreation', 1, 1, NULL, NULL),
	('prop_barbell_02', 'Barbell 110kg', 770, 2, 'recreation', 1, 1, NULL, NULL),
	('prop_barbell_100kg', 'Barbell 100kg', 700, 2, 'recreation', 1, 1, NULL, NULL),
	('prop_barbell_10kg', 'Barbell 10kg', 200, 1, 'recreation', 1, 1, NULL, NULL),
	('prop_barbell_20kg', 'Barbell 20kg', 260, 1, 'recreation', 1, 1, NULL, NULL),
	('prop_barbell_30kg', 'Barbell 30kg', 330, 1, 'recreation', 1, 1, NULL, NULL),
	('prop_barbell_40kg', 'Barbell 40kg', 390, 2, 'recreation', 1, 1, NULL, NULL),
	('prop_barbell_50kg', 'Barbell 50kg', 440, 1, 'recreation', 1, 1, NULL, NULL),
	('prop_barbell_60kg', 'Barbell 60kg', 510, 2, 'recreation', 1, 1, NULL, NULL),
	('prop_barbell_80kg', 'Barbell 80kg', 600, 2, 'recreation', 1, 1, NULL, NULL),
	('prop_basketball_net', 'Basketball Hoop', 1850, 3, 'recreation', 1, 1, NULL, NULL),
	('prop_bbq_1', 'BBQ', 4800, 2, 'outdoor', 1, 0, NULL, NULL),
	('prop_bbq_3', 'Brick BBQ', 5500, 3, 'outdoor', 1, 0, NULL, NULL),
	('prop_bbq_4', 'BBQ', 900, 2, 'outdoor', 1, 0, NULL, NULL),
	('prop_bbq_5', 'BBQ', 4500, 2, 'outdoor', 1, 0, NULL, NULL),
	('prop_beach_fire', 'Beach Campfire', 300, 1, 'outdoor', 1, 0, NULL, NULL),
	('prop_beach_lilo_02', 'Inflatable Pool Mattress', 240, 1, 'outdoor', 1, 0, NULL, NULL),
	('prop_beach_parasol_05', 'Beach Parasol (Striped)', 400, 3, 'outdoor', 1, 0, NULL, NULL),
	('prop_beach_ring_01', 'Inflatable Swim Ring', 200, 2, 'outdoor', 1, 0, NULL, NULL),
	('prop_beach_sandcas_04', 'Sandcastle', 100, 2, 'outdoor', 1, 0, NULL, NULL),
	('prop_bench_01a', 'Metal Bench (Classic)', 440, 3, 'outdoor', 1, 0, NULL, NULL),
	('prop_bench_01b', 'Metal Bench (Classic Blue)', 460, 3, 'outdoor', 1, 0, NULL, NULL),
	('prop_bench_01c', 'Metal Bench (Green)', 420, 3, 'outdoor', 1, 0, NULL, NULL),
	('prop_bench_02', 'Metal Park Bench', 400, 3, 'outdoor', 1, 0, NULL, NULL),
	('prop_bench_03', 'Industrial Metal Bench', 550, 3, 'outdoor', 1, 0, NULL, NULL),
	('prop_bench_04', 'Wooden Bench', 850, 2, 'outdoor', 1, 0, NULL, NULL),
	('prop_bench_06', 'Garden Bench (Slatted)', 600, 3, 'outdoor', 1, 0, NULL, NULL),
	('prop_bench_07', 'Minimalist Park Bench', 500, 3, 'outdoor', 1, 0, NULL, NULL),
	('prop_bench_08', 'Wooden Bench (Concrete legs)', 950, 3, 'outdoor', 1, 0, NULL, NULL),
	('prop_bench_10', 'Bus Stop Bench', 400, 3, 'outdoor', 1, 0, NULL, NULL),
	('prop_bench_11', 'Heavy Duty Bench', 500, 3, 'outdoor', 1, 0, NULL, NULL),
	('prop_beware_dog_sign', 'Dog Sign', 130, 1, 'decorations', 1, 0, NULL, NULL),
	('prop_bin_01a', 'Standard Trash Can', 180, 2, 'outdoor', 1, 0, NULL, NULL),
	('prop_bin_02a', 'Trash Can (Blue)', 120, 2, 'outdoor', 1, 0, NULL, NULL),
	('prop_bin_03a', 'Black Garbage Bin', 10, 2, 'outdoor', 1, 0, NULL, NULL),
	('prop_bin_04a', 'Commercial Trash Bin (Closed)', 300, 2, 'outdoor', 1, 0, NULL, NULL),
	('prop_bin_05a', 'Dumpster Bin (Blue)', 280, 2, 'outdoor', 1, 0, NULL, NULL),
	('prop_bin_06a', 'Industrial Garbage Bin', 180, 2, 'outdoor', 1, 0, NULL, NULL),
	('prop_bin_07a', 'Metal Trash Can (Empty)', 300, 2, 'outdoor', 1, 0, NULL, NULL),
	('prop_bin_07b', 'Metal Trash Can (Closed)', 300, 2, 'outdoor', 1, 0, NULL, NULL),
	('prop_bin_07c', 'Trash Can (Half-closed)', 300, 2, 'outdoor', 1, 0, NULL, NULL),
	('prop_bin_07d', 'Graffiti Trash Can', 200, 2, 'outdoor', 1, 0, NULL, NULL),
	('prop_bin_08a', 'Tall Public Bin', 300, 2, 'outdoor', 1, 0, NULL, NULL),
	('prop_bin_08open', 'Tall Public Bin (Open)', 300, 2, 'outdoor', 1, 0, NULL, NULL),
	('prop_bin_09a', 'Tall Trash Can (With Lid)', 80, 3, 'outdoor', 1, 0, NULL, NULL),
	('prop_bin_10a', 'Bin (Dark Blue)', 200, 1, 'outdoor', 1, 0, NULL, NULL),
	('prop_bin_10b', 'Bin (Red)', 200, 1, 'outdoor', 1, 0, NULL, NULL),
	('prop_bin_11a', 'Street Bin (Yellow)', 160, 1, 'outdoor', 1, 0, NULL, NULL),
	('prop_bin_11b', 'Street Bin (Green)', 160, 1, 'outdoor', 1, 0, NULL, NULL),
	('prop_bin_12a', 'City Trash Can (Metal Base)', 400, 1, 'outdoor', 1, 0, NULL, NULL),
	('prop_bin_delpiero', 'Del Perro Promenade Trash Bin', 500, 2, 'outdoor', 1, 0, NULL, NULL),
	('prop_bin_delpiero_b', 'Del Perro Trash Bin (Decorative)', 400, 3, 'outdoor', 1, 0, NULL, NULL),
	('prop_cabinet_01', 'White Cabinet (Tall, Drawers)', 7000, 2, 'storage', 1, 1, 'storage', '{"slots":10,"weight":10000}'),
	('prop_cabinet_02b', 'Filing Cabinet (3 Drawers, Beige)', 6000, 2, 'storage', 0, 1, 'storage', '{"slots":10,"weight":10000}'),
	('prop_cctv_cam_04c', 'CCTV Camera (Ceiling Dome)', 12000, 1, 'electronic', 1, 1, NULL, NULL),
	('prop_cctv_cam_05a', 'CCTV Camera (Ceiling Tube)', 13000, 1, 'electronic', 1, 1, NULL, NULL),
	('prop_cctv_cam_06a', 'CCTV Camera (Wall Box)', 14000, 1, 'electronic', 1, 1, NULL, NULL),
	('prop_chair_01a', 'Metal Chair (Blue Frame)', 250, 2, 'chair', 1, 1, NULL, NULL),
	('prop_chair_01b', 'Plastic Chair (Worn Red)', 280, 2, 'chair', 1, 1, NULL, NULL),
	('prop_chair_02', 'Wicker Chair (Dark)', 380, 2, 'chair', 1, 1, NULL, NULL),
	('prop_chair_03', 'Antique Dining Chair (Round Back)', 220, 2, 'chair', 1, 1, NULL, NULL),
	('prop_chair_04a', 'Modern Chair (Striped Back)', 740, 2, 'chair', 1, 1, NULL, NULL),
	('prop_chair_04b', 'Modern Chair (Flat Back)', 700, 2, 'chair', 1, 1, NULL, NULL),
	('prop_chair_05', 'Classic Wicker Chair', 470, 2, 'chair', 1, 1, NULL, NULL),
	('prop_chair_06', 'Dining Chair (Dark Red)', 290, 2, 'chair', 1, 1, NULL, NULL),
	('prop_chair_07', 'Vintage Wooden Chair', 220, 2, 'chair', 1, 1, NULL, NULL),
	('prop_chair_08', 'Plastic Chair (White Legs)', 200, 2, 'chair', 1, 1, NULL, NULL),
	('prop_chair_09', 'Rattan Chair (Green Weave)', 300, 2, 'chair', 1, 1, NULL, NULL),
	('prop_chair_10', 'Ornate Armchair (Vintage)', 300, 2, 'chair', 1, 1, NULL, NULL),
	('prop_chateau_chair_01', 'Antique Chateau Armchair', 290, 2, 'chair', 1, 1, NULL, NULL),
	('prop_clown_chair', 'Circus-Style Wooden Chair', 190, 1, 'chair', 1, 1, NULL, NULL),
	('prop_copier_01', 'Office Copier (Open Tray)', 700, 3, 'electronic', 0, 1, NULL, NULL),
	('prop_couch_01', 'Two-Seat Sofa (Pillows)', 1500, 3, 'sofa', 1, 0, NULL, NULL),
	('prop_couch_03', 'Rustic Couch (Beige Cushions)', 1300, 3, 'sofa', 1, 0, NULL, NULL),
	('prop_couch_lg_02', 'Modern Couch (Wood Trim)', 2500, 3, 'sofa', 1, 1, NULL, NULL),
	('prop_couch_lg_05', 'Fabric Couch (Gray/Brown)', 2700, 3, 'sofa', 1, 0, NULL, NULL),
	('prop_couch_lg_06', 'Vintage Couch (Red/Brown)', 1700, 3, 'sofa', 1, 0, NULL, NULL),
	('prop_couch_lg_07', 'Couch with Pillows (Gray/Orange)', 2900, 3, 'sofa', 0, 1, NULL, NULL),
	('prop_couch_lg_08', 'Modern Couch (Brown/Gray)', 4100, 3, 'sofa', 0, 1, NULL, NULL),
	('prop_couch_sm1_07', 'L-Shaped Sofa (Left Side)', 490, 2, 'sofa', 0, 1, NULL, NULL),
	('prop_couch_sm2_07', 'L-Shaped Sofa (Right Side)', 490, 2, 'sofa', 0, 1, NULL, NULL),
	('prop_couch_sm_02', 'Compact Couch (Brown Fabric)', 720, 2, 'sofa', 1, 1, NULL, NULL),
	('prop_couch_sm_05', 'Compact Couch (Beige Fabric)', 900, 3, 'sofa', 1, 1, NULL, NULL),
	('prop_couch_sm_06', 'Compact Sofa (Gray)', 700, 3, 'sofa', 1, 1, NULL, NULL),
	('prop_couch_sm_07', 'Vintage Leather Sofa', 2000, 3, 'sofa', 1, 1, NULL, NULL),
	('prop_cs_keyboard_01', 'Keyboard (Black)', 480, 1, 'electronic', 1, 1, NULL, NULL),
	('prop_cs_tv_stand', 'TV Stand with Screen', 2000, 3, 'electronic', 1, 1, NULL, NULL),
	('prop_dart_bd_01', 'Dartboard (Wood Backing)', 400, 1, 'recreation', 1, 1, NULL, NULL),
	('prop_dart_bd_cab_01', 'Dartboard with Cabinet', 550, 2, 'recreation', 1, 1, NULL, NULL),
	('prop_doghouse_01', 'Wooden Doghouse', 750, 3, 'outdoor', 1, 0, NULL, NULL),
	('prop_dyn_pc', 'Desktop Computer (Tower)', 2000, 1, 'electronic', 0, 1, NULL, NULL),
	('prop_exer_bike_01', 'Exercise Bike (Stationary)', 1600, 3, 'recreation', 1, 1, NULL, NULL),
	('prop_fan_01', 'Oscillating Fan (Floor)', 400, 2, 'electronic', 1, 1, NULL, NULL),
	('prop_fax_01', 'Office Fax Machine', 400, 1, 'electronic', 0, 1, NULL, NULL),
	('prop_fbi3_coffee_table', 'Modern Coffee Table (White Frame)', 1200, 1, 'table', 1, 1, NULL, NULL),
	('prop_ff_shelves_01', 'Warehouse Shelving Unit (Metal)', 10000, 3, 'storage', 1, 1, 'storage', '{"slots":10,"weight":10000}'),
	('prop_fib_ashtray_01', 'FIB Ashtray (Wall-Mounted)', 25, 1, 'decorations', 1, 1, NULL, NULL),
	('prop_flamingo', 'Pink Flamingo (Lawn Ornament)', 400, 1, 'outdoor', 1, 0, NULL, NULL),
	('prop_folder_02', 'Magazine Holder (Black)', 40, 1, 'decorations', 1, 1, NULL, NULL),
	('prop_foodprocess_01', 'Blender / Food Processor', 170, 1, 'kitchen', 0, 1, NULL, NULL),
	('prop_fountain2', 'Stone Fountain (Round)', 8500, 3, 'outdoor', 1, 0, NULL, NULL),
	('prop_fridge_03', 'Tall Fridge (Closed)', 8500, 3, 'kitchen', 0, 1, 'storage', '{"weight":8000,"slots":8}'),
	('prop_game_clock_01', 'Wall Clock (White Face)', 100, 1, 'decorations', 0, 1, NULL, NULL),
	('prop_game_clock_02', 'Wall Clock (Black Face)', 120, 1, 'decorations', 0, 1, NULL, NULL),
	('prop_gazebo_01', 'Gazebo Tent (Open Sides)', 3800, 3, 'outdoor', 1, 0, NULL, NULL),
	('prop_gazebo_02', 'Gazebo Tent (Side Walls)', 3800, 3, 'outdoor', 1, 0, NULL, NULL),
	('prop_gazebo_03', 'Gazebo Tent (No Walls)', 3800, 3, 'outdoor', 1, 0, NULL, NULL),
	('prop_gc_chair02', 'Basic Chair (Plastic Seat)', 195, 2, 'chair', 1, 1, NULL, NULL),
	('prop_ghettoblast_01', 'Boombox Radio (Retro)', 1500, 1, 'electronic', 1, 1, NULL, NULL),
	('prop_gnome1', 'Garden Gnome (Smiling)', 300, 1, 'outdoor', 1, 0, NULL, NULL),
	('prop_gnome2', 'Garden Gnome (Lantern)', 300, 1, 'outdoor', 1, 0, NULL, NULL),
	('prop_gnome3', 'Garden Gnome (Digging)', 300, 1, 'outdoor', 1, 0, NULL, NULL),
	('prop_gravestones_10a', 'Gravestone Statue (Angel Wings)', 6000, 3, 'decorations', 1, 0, NULL, NULL),
	('prop_handdry_01', 'Wall Cabinet (White, Small)', 60, 1, 'decorations', 1, 1, NULL, NULL),
	('prop_hottub2', 'Wooden Hot Tub (Lid Closed)', 9000, 3, 'outdoor', 1, 0, NULL, NULL),
	('prop_inout_tray_02', 'Stacked Document Trays (3x)', 80, 1, 'decorations', 1, 1, NULL, NULL),
	('prop_kayak_01b', 'Inflatable Kayak (Yellow)', 400, 2, 'outdoor', 1, 0, NULL, NULL),
	('prop_kettle', 'Electric Kettle (Silver)', 140, 1, 'kitchen', 0, 1, NULL, NULL),
	('prop_keyboard_01a', 'Keyboard (White)', 480, 1, 'electronic', 1, 1, NULL, NULL),
	('prop_kitch_juicer', 'Electric Juicer', 200, 1, 'kitchen', 0, 1, NULL, NULL),
	('prop_kitch_pot_fry', 'Frying Pan (Shallow)', 60, 1, 'kitchen', 1, 1, NULL, NULL),
	('prop_kitch_pot_lrg2', 'Cooking Pot (Large)', 80, 1, 'kitchen', 1, 1, NULL, NULL),
	('prop_knife', 'Kitchen Knife (Used)', 50, 1, 'kitchen', 1, 1, NULL, NULL),
	('prop_laptop_01a', 'Laptop (Open, Green Wallpaper)', 3200, 1, 'electronic', 1, 1, 'device', NULL),
	('prop_ld_farm_table01', 'Low Farmhouse Table (Dark Wood)', 1500, 3, 'table', 1, 1, NULL, NULL),
	('prop_ld_farm_table02', 'Low Farm Table (Dark Wood)', 1400, 2, 'table', 1, 1, NULL, NULL),
	('prop_lime_jar', 'Jar of Lime', 35, 1, 'kitchen', 1, 1, NULL, NULL),
	('prop_micro_01', 'Microwave (Basic, White)', 850, 1, 'electronic', 0, 1, NULL, NULL),
	('prop_micro_02', 'Microwave (Digital, White)', 950, 1, 'electronic', 0, 1, NULL, NULL),
	('prop_micro_04', 'Microwave (Wooden Casing)', 800, 1, 'electronic', 0, 1, NULL, NULL),
	('prop_monitor_01c', 'Monitor (Windows XP Style)', 2000, 1, 'electronic', 0, 1, 'device', NULL),
	('prop_monitor_01d', 'Monitor (Gameshow Display)', 2200, 1, 'electronic', 0, 1, 'device', NULL),
	('prop_monitor_li', 'Monitor (Lifeinvader UI)', 2200, 1, 'electronic', 0, 1, 'device', NULL),
	('prop_monitor_w_large', 'Wide Office Monitor', 3100, 1, 'electronic', 0, 1, 'device', NULL),
	('prop_mouse_02', 'Mouse (Standard, Right)', 90, 1, 'electronic', 0, 1, NULL, NULL),
	('prop_muscle_bench_01', 'Workout Bench (Flat)', 600, 2, 'recreation', 1, 1, NULL, NULL),
	('prop_muscle_bench_03', 'Workout Bench (Inclined)', 1200, 3, 'recreation', 1, 1, NULL, NULL),
	('prop_muscle_bench_05', 'Workout Machine (Arms & Pull)', 1500, 3, 'recreation', 1, 1, NULL, NULL),
	('prop_office_desk_01', 'Office Desk (Drawers, Gray)', 1850, 2, 'table', 1, 1, NULL, NULL),
	('prop_office_phone_tnt', 'Office Telephone (TNT Model)', 200, 1, 'electronic', 0, 1, NULL, NULL),
	('prop_off_chair_01', 'Office Chair (High Back)', 650, 2, 'chair', 1, 1, NULL, NULL),
	('prop_off_chair_03', 'Office Chair (Padded, Gray)', 300, 2, 'chair', 1, 1, NULL, NULL),
	('prop_off_chair_04', 'Office Chair (Worn Fabric)', 300, 2, 'chair', 1, 1, NULL, NULL),
	('prop_off_chair_04b', 'Office Chair (Low Back, Gray)', 350, 2, 'chair', 1, 1, NULL, NULL),
	('prop_off_chair_05', 'Office Chair (Mesh Armrests)', 450, 2, 'chair', 1, 1, NULL, NULL),
	('prop_old_deck_chair', 'Folding Lounge Chair (Blue)', 160, 2, 'chair', 1, 1, NULL, NULL),
	('prop_old_wood_chair', 'Wooden Armchair (Gray, Aged)', 160, 2, 'chair', 1, 1, NULL, NULL),
	('prop_old_wood_chair_lod', 'Old Wooden Chair (LOD)', 180, 2, 'chair', 1, 1, NULL, NULL),
	('prop_palm_med_01a', 'Palm Tree (Tall, Full)', 3250, 3, 'plant', 1, 0, NULL, NULL),
	('prop_palm_med_01b', 'Palm Tree (Tall, Curved)', 3100, 3, 'plant', 1, 0, NULL, NULL),
	('prop_palm_med_01c', 'Palm Tree (Medium Height, Wide)', 3000, 3, 'plant', 1, 0, NULL, NULL),
	('prop_palm_med_01d', 'Palm Tree (Leaning Right)', 2300, 3, 'plant', 1, 0, NULL, NULL),
	('prop_palm_sm_01a', 'Palm Tree (Small Decorative)', 3000, 3, 'plant', 1, 0, NULL, NULL),
	('prop_palm_sm_01d', 'Palm Tree (Small, Dense)', 2400, 3, 'plant', 1, 0, NULL, NULL),
	('prop_palm_sm_01e', 'Palm Tree (Small, Thin)', 3000, 3, 'plant', 1, 0, NULL, NULL),
	('prop_palm_sm_01f', 'Palm Tree (Small, Thick)', 2800, 3, 'plant', 1, 0, NULL, NULL),
	('prop_parasol_01', 'Parasol (Light Gray Fabric)', 800, 3, 'outdoor', 1, 0, NULL, NULL),
	('prop_parasol_01b_lod', 'Parasol (Dark Base, Lod Style)', 800, 3, 'outdoor', 1, 0, NULL, NULL),
	('prop_parasol_01_b', 'Parasol (Dark Blue Fabric)', 800, 3, 'outdoor', 1, 0, NULL, NULL),
	('prop_parasol_01_c', 'Parasol (Brown, Weathered)', 600, 3, 'outdoor', 1, 0, NULL, NULL),
	('prop_parasol_01_lod', 'Parasol (Light Gray, Lod Style)', 850, 3, 'outdoor', 1, 0, NULL, NULL),
	('prop_parasol_02', 'Parasol (White, Tilted)', 800, 3, 'outdoor', 1, 0, NULL, NULL),
	('prop_parasol_02_b', 'Parasol (Green Fabric)', 800, 3, 'outdoor', 1, 0, NULL, NULL),
	('prop_parasol_02_c', 'Parasol (Dark Blue Fabric)', 800, 3, 'outdoor', 1, 0, NULL, NULL),
	('prop_parasol_03', 'Parasol (Blue, Wide)', 600, 3, 'outdoor', 1, 0, NULL, NULL),
	('prop_parasol_03_b', 'Parasol (Yellow with Branding)', 600, 3, 'outdoor', 1, 0, NULL, NULL),
	('prop_parasol_03_c', 'Parasol (Green with Branding)', 600, 3, 'outdoor', 1, 0, NULL, NULL),
	('prop_parasol_04c', 'Parasol (Red/White Sprunk Branding)', 600, 3, 'outdoor', 1, 0, NULL, NULL),
	('prop_parasol_04d', 'Parasol (Green/White Sprunk Branding)', 600, 3, 'outdoor', 1, 0, NULL, NULL),
	('prop_patio_lounger1', 'Patio Lounger (Beige Cushion)', 900, 3, 'chair', 1, 1, NULL, NULL),
	('prop_patio_lounger1b', 'Patio Lounger (No Cushion)', 800, 2, 'chair', 1, 1, NULL, NULL),
	('prop_patio_lounger1_table', 'Patio Table (Wooden)', 900, 1, 'table', 1, 1, NULL, NULL),
	('prop_patio_lounger_2', 'Green Patio Lounger (Foldable)', 800, 3, 'chair', 1, 1, NULL, NULL),
	('prop_patio_lounger_3', 'Patio Lounger (White)', 500, 3, 'chair', 1, 1, NULL, NULL),
	('prop_pc_02a', 'Old PC Tower (Beige)', 1600, 1, 'electronic', 0, 1, NULL, NULL),
	('prop_picnictable_01', 'Wooden Picnic Table (Standard)', 680, 3, 'table', 1, 1, NULL, NULL),
	('prop_picnictable_01_lod', 'Wooden Picnic Table (LOD)', 500, 3, 'table', 1, 1, NULL, NULL),
	('prop_picnictable_02', 'Wooden Picnic Table (Red Accents)', 900, 3, 'table', 1, 1, NULL, NULL),
	('prop_plant_interior_05a', 'Rectangular Interior Planter', 600, 3, 'plant', 1, 1, NULL, NULL),
	('prop_plant_int_01a', 'Indoor Plant (Short, Round Pot)', 360, 3, 'plant', 1, 1, NULL, NULL),
	('prop_plant_int_01b', 'Indoor Plant (Tall, Brown Pot)', 340, 3, 'plant', 1, 1, NULL, NULL),
	('prop_plant_int_02a', 'Topiary Ball (Square Pot)', 420, 3, 'plant', 1, 1, NULL, NULL),
	('prop_plant_int_02b', 'Topiary Ball (Round Pot)', 460, 3, 'plant', 1, 1, NULL, NULL),
	('prop_plant_int_03a', 'Indoor Fern (Stone Pot)', 330, 3, 'plant', 1, 1, NULL, NULL),
	('prop_plant_int_03b', 'Indoor Plant (Tall, White Pot)', 285, 3, 'plant', 1, 1, NULL, NULL),
	('prop_plant_int_03c', 'Indoor Plant (Pointed, Tall)', 250, 3, 'plant', 1, 1, NULL, NULL),
	('prop_plant_int_04a', 'Wide Indoor Plant (Low Pot)', 310, 2, 'plant', 1, 1, NULL, NULL),
	('prop_plant_int_04b', 'Indoor Bush (Flat Base)', 340, 2, 'plant', 1, 1, NULL, NULL),
	('prop_plant_int_04c', 'Leafy Plant (Round Pot)', 120, 3, 'plant', 1, 1, NULL, NULL),
	('prop_plant_int_05a', 'Wicker Planter with Flowers', 590, 3, 'plant', 1, 1, NULL, NULL),
	('prop_plant_int_05b', 'Basket Plant (Rectangular)', 400, 3, 'plant', 1, 1, NULL, NULL),
	('prop_plant_int_06a', 'Rectangular Planter (Tall Grass)', 550, 3, 'plant', 1, 1, NULL, NULL),
	('prop_plant_int_06b', 'Planter with Dense Shrub', 700, 3, 'plant', 1, 1, NULL, NULL),
	('prop_plant_int_06c', 'Boxwood Hedge Planter', 500, 3, 'plant', 1, 1, NULL, NULL),
	('prop_pooltable_02', 'Modern Pool Table (Gray Trim)', 3300, 3, 'recreation', 1, 1, NULL, NULL),
	('prop_pooltable_3b', 'Pool Table (Purple)', 3600, 3, 'recreation', 1, 1, NULL, NULL),
	('prop_portable_hifi_01', 'Portable Hi-Fi (Boombox)', 330, 1, 'electronic', 1, 1, NULL, NULL),
	('prop_pot_03', 'Cooking Pot (Medium Size)', 60, 1, 'kitchen', 1, 1, NULL, NULL),
	('prop_pot_plant_01a', 'Indoor Plant (White Pot, Small)', 200, 3, 'plant', 1, 1, NULL, NULL),
	('prop_pot_plant_01b', 'Indoor Plant (Dark Pot, Spiked Leaves)', 280, 3, 'plant', 1, 1, NULL, NULL),
	('prop_pot_plant_01c', 'Indoor Plant (Tall, Curved Leaves)', 290, 3, 'plant', 1, 1, NULL, NULL),
	('prop_pot_plant_01d', 'Fan Palm (Short, Black Pot)', 340, 3, 'plant', 1, 1, NULL, NULL),
	('prop_pot_plant_01e', 'Fan Palm (Small, Gray Pot)', 300, 3, 'plant', 1, 1, NULL, NULL),
	('prop_pot_plant_02a', 'Round Pot with Shrub (Stone)', 390, 3, 'plant', 1, 1, NULL, NULL),
	('prop_pot_plant_02b', 'Planter with Flowers (Round, Tall)', 450, 3, 'plant', 1, 1, NULL, NULL),
	('prop_pot_plant_02c', 'Planter with Pink Flowers (Round)', 450, 3, 'plant', 1, 1, NULL, NULL),
	('prop_pot_plant_02d', 'Small Shrub in Round Pot', 350, 3, 'plant', 1, 1, NULL, NULL),
	('prop_pot_plant_03a', 'Cone Topiary (White Pot)', 550, 3, 'plant', 1, 1, NULL, NULL),
	('prop_pot_plant_03b', 'Shrub in Terracotta Pot', 480, 3, 'plant', 1, 1, NULL, NULL),
	('prop_pot_plant_03c', 'Topiary (Pedestal Pot)', 430, 3, 'plant', 1, 1, NULL, NULL),
	('prop_pot_plant_04a', 'Window Box Planter (Shrubs)', 365, 3, 'plant', 1, 1, NULL, NULL),
	('prop_pot_plant_04b', 'Ornamental Plant (Yellow Pot)', 620, 3, 'plant', 1, 1, NULL, NULL),
	('prop_pot_plant_04c', 'Ornamental Palm (Wide Pot)', 500, 3, 'plant', 1, 1, NULL, NULL),
	('prop_pot_plant_05a', 'Long Thin Plant (White Base)', 220, 3, 'plant', 1, 1, NULL, NULL),
	('prop_pot_plant_05b', 'Tall Cone Topiary (Gray Pot)', 530, 3, 'plant', 1, 1, NULL, NULL),
	('prop_pot_plant_05c', 'Rectangular Marble Planter', 850, 3, 'plant', 1, 1, NULL, NULL),
	('prop_pot_plant_05d', 'Round Stone Planter (Decorative)', 800, 3, 'plant', 1, 1, NULL, NULL),
	('prop_pot_plant_05d_l1', 'Stone Planter with Flowers', 900, 3, 'plant', 1, 1, NULL, NULL),
	('prop_pot_plant_6a', 'Hanging Fern Basket', 600, 3, 'plant', 1, 1, NULL, NULL),
	('prop_pot_plant_bh1', 'Small Bush in Ceramic Pot', 330, 3, 'plant', 1, 1, NULL, NULL),
	('prop_pot_plant_inter_03a', 'Indoor Tall Plant (Minimalist)', 360, 3, 'plant', 1, 1, NULL, NULL),
	('prop_printer_01', 'Office Printer (Closed Lid)', 450, 1, 'electronic', 0, 1, NULL, NULL),
	('prop_proxy_chateau_table', 'Wooden Round Table (Chateau Style)', 800, 3, 'table', 1, 1, NULL, NULL),
	('prop_punch_bag_l', 'Punching Bag (Hanging)', 1800, 2, 'recreation', 1, 1, NULL, NULL),
	('prop_recyclebin_01a', 'Recycle Bin (Blue)', 300, 1, 'outdoor', 1, 0, NULL, NULL),
	('prop_recyclebin_02a', 'Recycle Bin (Red – Mixed Plastic)', 300, 1, 'outdoor', 1, 0, NULL, NULL),
	('prop_recyclebin_02b', 'Recycle Bin (Yellow – Cans Only)', 300, 1, 'outdoor', 1, 0, NULL, NULL),
	('prop_recyclebin_03_a', 'Classic Bin', 200, 2, 'outdoor', 1, 0, NULL, NULL),
	('prop_rub_binbag_01', 'Black Garbage Bag (Full)', 10, 2, 'decorations', 1, 1, NULL, NULL),
	('prop_rub_cabinet02', 'Wooden Shelf (Open, Aged)', 6100, 3, 'storage', 1, 1, 'storage', '{"slots":10,"weight":10000}'),
	('prop_rub_matress_01', 'Mattress (Old, Dirty)', 750, 2, 'bed', 1, 1, NULL, NULL),
	('prop_rub_table_01', 'Old Wooden Table (Worn)', 350, 2, 'table', 1, 1, NULL, NULL),
	('prop_rub_table_02', 'Rustic Wooden Table (Damaged)', 310, 3, 'table', 1, 1, NULL, NULL),
	('prop_rus_olive', 'Bushy Olive Shrub', 430, 3, 'plant', 1, 1, NULL, NULL),
	('prop_rus_olive_l2', 'Olive Tree (Large)', 800, 3, 'plant', 1, 0, NULL, NULL),
	('prop_rus_olive_wint', 'Winter Olive Tree', 2200, 3, 'plant', 1, 0, NULL, NULL),
	('prop_sapling_break_01', 'Young Sapling Tree (Thin)', 2100, 3, 'plant', 1, 0, NULL, NULL),
	('prop_sapling_break_02', 'Tall Sapling (Pointed)', 2400, 2, 'plant', 1, 1, NULL, NULL),
	('prop_shower_rack_01', 'Shower Rack (3 Shelves)', 80, 1, 'bathroom', 0, 1, NULL, NULL),
	('prop_shrub_rake', 'Garden Rake (Green)', 90, 1, 'outdoor', 1, 0, NULL, NULL),
	('prop_sink_02', 'Metal Sink (Wall Mounted)', 300, 1, 'bathroom', 0, 1, NULL, NULL),
	('prop_sink_05', 'Bathroom Sink (Rounded)', 280, 1, 'bathroom', 0, 1, NULL, NULL),
	('prop_sink_06', 'Bathroom Sink (Tall Pedestal)', 250, 1, 'bathroom', 0, 1, NULL, NULL),
	('prop_skid_chair_01', 'Camping Chair (Dark Green)', 430, 2, 'chair', 1, 1, NULL, NULL),
	('prop_skid_chair_02', 'Camping Chair (Blue Fabric)', 430, 2, 'chair', 1, 1, NULL, NULL),
	('prop_skid_chair_03', 'Camping Chair (Plaid)', 430, 2, 'chair', 1, 1, NULL, NULL),
	('prop_skid_tent_01', 'Camping Tent (Folded)', 800, 3, 'outdoor', 1, 0, NULL, NULL),
	('prop_soap_disp_01', 'Wall Soap Dispenser', 220, 1, 'bathroom', 0, 1, NULL, NULL),
	('prop_sol_chair', 'Classic Armchair (Leather, Worn)', 1650, 3, 'chair', 1, 1, NULL, NULL),
	('prop_speaker_01', 'Speaker Panel (Vertical, LED)', 1450, 1, 'electronic', 0, 1, NULL, NULL),
	('prop_speaker_02', 'Tall Wooden Speaker (Hi-Fi)', 1200, 1, 'electronic', 0, 1, NULL, NULL),
	('prop_speaker_06', 'Large Black Speaker', 2000, 1, 'electronic', 0, 1, NULL, NULL),
	('prop_speaker_07', 'Party Speaker (Dual)', 550, 1, 'electronic', 1, 1, NULL, NULL),
	('prop_speedball_01', 'Speedball Lamp (Modern)', 1400, 2, 'recreation', 1, 1, NULL, NULL),
	('prop_sponge_01', 'Cleaning Sponge (Yellow)', 20, 1, 'decorations', 1, 1, NULL, NULL),
	('prop_sports_clock_01', 'Wall Clock (Sport Design)', 130, 1, 'decorations', 0, 1, NULL, NULL),
	('prop_stickbfly', 'Butterfly Decoration (Purple)', 90, 1, 'outdoor', 1, 0, NULL, NULL),
	('prop_stickhbird', 'Bird Decoration (Small, Brown)', 90, 1, 'outdoor', 1, 0, NULL, NULL),
	('prop_stoneshroom1', 'Mushroom Decoration (Purple Glow)', 120, 1, 'outdoor', 1, 0, NULL, NULL),
	('prop_stoneshroom2', 'Mushroom Decoration (Blue Glow)', 120, 1, 'outdoor', 1, 0, NULL, NULL),
	('prop_stool_01', 'Bar Stool (Metal)', 280, 1, 'chair', 1, 1, NULL, NULL),
	('prop_suitcase_01', 'Suitcase (Black)', 5500, 1, 'storage', 1, 1, 'storage', '{"weight":10000,"slots":5}'),
	('prop_suitcase_01b', 'Suitcase (Brown)', 5500, 1, 'storage', 1, 1, 'storage', '{"weight":10000,"slots":5}'),
	('prop_suitcase_01c', 'Suitcase (Red)', 5500, 1, 'storage', 1, 1, 'storage', '{"weight":10000,"slots":5}'),
	('prop_suitcase_01d', 'Suitcase (Dark Gray)', 5500, 1, 'storage', 1, 1, 'storage', '{"weight":10000,"slots":5}'),
	('prop_suitcase_02', 'Double Suitcase (Stacked)', 3500, 1, 'storage', 1, 1, 'storage', '{"weight":10000,"slots":5}'),
	('prop_suitcase_03', 'Double Suitcase (Red + Black)', 3500, 1, 'storage', 1, 1, 'storage', '{"weight":10000,"slots":3}'),
	('prop_suitcase_03b', 'Double Suitcase (Black)', 3500, 1, 'storage', 1, 1, 'storage', '{"weight":10000,"slots":3}'),
	('prop_tablesmall_01', 'Low Wooden Table (Small)', 2000, 2, 'table', 1, 1, NULL, NULL),
	('prop_table_01', 'Coffee Table (Wooden)', 3400, 3, 'table', 1, 1, NULL, NULL),
	('prop_table_01_chr_a', 'Wooden Chair (With Armrests)', 350, 2, 'chair', 1, 1, NULL, NULL),
	('prop_table_01_chr_b', 'Wooden Chair (No Armrests)', 320, 2, 'chair', 1, 1, NULL, NULL),
	('prop_table_02', 'Round Table (Wood + Iron Base)', 1200, 3, 'table', 1, 1, NULL, NULL),
	('prop_table_02_chr', 'Wooden Chair (Dark Wood)', 300, 2, 'chair', 1, 1, NULL, NULL),
	('prop_table_03', 'Plastic Table (White)', 950, 3, 'table', 1, 1, NULL, NULL),
	('prop_table_03b', 'Plastic Table (Square, White)', 600, 3, 'table', 1, 1, NULL, NULL),
	('prop_table_03b_chr', 'Plastic Chair (Wide Back, White)', 220, 2, 'chair', 1, 1, NULL, NULL),
	('prop_table_03b_cs', 'Plastic Table (Square, White)', 600, 3, 'table', 1, 1, NULL, NULL),
	('prop_table_03_chr', 'Plastic Chair (Armrest, White)', 220, 2, 'chair', 1, 1, NULL, NULL),
	('prop_table_04', 'Dining Bench (Dark Frame)', 3000, 3, 'table', 1, 1, NULL, NULL),
	('prop_table_04_chr', 'Dining Chair (Metal Frame)', 380, 2, 'chair', 1, 1, NULL, NULL),
	('prop_table_05', 'Round Dining Table (Wicker)', 720, 3, 'table', 1, 1, NULL, NULL),
	('prop_table_05_chr', 'Wicker Chair (Dining)', 330, 2, 'chair', 1, 1, NULL, NULL),
	('prop_table_06', 'Modern Dining Table (Metal Legs)', 1400, 3, 'table', 1, 1, NULL, NULL),
	('prop_table_06_chr', 'Chair (Thin Metal Frame)', 650, 2, 'chair', 1, 1, NULL, NULL),
	('prop_table_07', 'Round Table with Pole', 620, 2, 'table', 1, 1, NULL, NULL),
	('prop_table_08', 'Old Wooden Table with Cover', 500, 3, 'table', 1, 1, NULL, NULL),
	('prop_table_para_comb_01', 'Parasol Table (Wood, Red Canopy)', 1200, 3, 'table', 1, 1, NULL, NULL),
	('prop_table_para_comb_03', 'Parasol Table (Blue Canopy)', 1200, 3, 'table', 1, 1, NULL, NULL),
	('prop_table_para_comb_04', 'Parasol Table (Gray Fabric)', 1300, 3, 'table', 1, 1, NULL, NULL),
	('prop_table_tennis', 'Table Tennis Table (Foldable)', 2100, 3, 'table', 1, 1, NULL, NULL),
	('prop_toaster_01', 'Toaster (Stainless)', 400, 1, 'kitchen', 0, 1, NULL, NULL),
	('prop_toaster_02', 'Toaster (White)', 330, 1, 'kitchen', 0, 1, NULL, NULL),
	('prop_toilet_01', 'Toilet (Standard)', 350, 1, 'bathroom', 0, 1, NULL, NULL),
	('prop_toilet_02', 'Toilet (Modern)', 500, 1, 'bathroom', 0, 1, NULL, NULL),
	('prop_toilet_brush_01', 'Toilet Brush (Holder)', 25, 1, 'bathroom', 0, 1, NULL, NULL),
	('prop_toilet_soap_02', 'Toilet Soap (With Dish)', 30, 1, 'bathroom', 0, 1, NULL, NULL),
	('prop_toilet_soap_04', 'Soap Dispenser (Pink)', 50, 1, 'bathroom', 0, 1, NULL, NULL),
	('prop_toothpaste_01', 'Toothpaste Tube', 20, 1, 'bathroom', 0, 1, NULL, NULL),
	('prop_towel_01', 'Towel Stack (White)', 40, 1, 'bathroom', 0, 1, NULL, NULL),
	('prop_trev_tv_01', 'CRT TV (Wooden Frame)', 140, 1, 'electronic', 1, 1, NULL, NULL),
	('prop_tv_01', 'TV (Black Screen)', 680, 1, 'electronic', 1, 1, NULL, NULL),
	('prop_tv_02', 'TV', 550, 1, 'electronic', 1, 1, NULL, NULL),
	('prop_tv_03', 'CRT TV (Dark Gray)', 150, 1, 'electronic', 1, 1, NULL, NULL),
	('prop_tv_04', 'CRT TV (Retro, Gray)', 120, 1, 'electronic', 1, 1, NULL, NULL),
	('prop_tv_05', 'Vintage TV (Antenna)', 700, 1, 'electronic', 1, 1, NULL, NULL),
	('prop_tv_06', 'CRT TV (Angled Edges)', 200, 1, 'electronic', 1, 1, NULL, NULL),
	('prop_tv_07', 'CRT TV (Beveled Frame)', 180, 1, 'electronic', 1, 1, NULL, NULL),
	('prop_tv_cabinet_03', 'TV Cabinet (Open Shelves)', 6900, 2, 'storage', 1, 1, 'storage', '{"weight":10000,"slots":10}'),
	('prop_tv_cabinet_04', 'TV Cabinet (Bookshelf Style)', 6400, 2, 'storage', 1, 1, 'storage', '{"weight":10000,"slots":10}'),
	('prop_tv_cabinet_05', 'TV Cabinet (Curved Front)', 6200, 2, 'storage', 1, 1, 'storage', '{"slots":10,"weight":10000}'),
	('prop_tv_flat_01', 'Flat TV (Modern, On Stand)', 3700, 2, 'electronic', 0, 1, NULL, NULL),
	('prop_tv_flat_02', 'Flat TV (Modern, Wide)', 3000, 1, 'electronic', 0, 1, NULL, NULL),
	('prop_tv_flat_02b', 'Flat TV (Wide, Black Frame)', 1300, 1, 'electronic', 0, 1, NULL, NULL),
	('prop_tv_flat_03', 'Flat TV (Modern Stand)', 1500, 1, 'electronic', 0, 1, NULL, NULL),
	('prop_tv_flat_03b', 'Flat TV (Stand, No Logo)', 4000, 1, 'electronic', 0, 1, NULL, NULL),
	('prop_tv_flat_michael', 'Flat TV (Michael\'s Room)', 3800, 1, 'electronic', 0, 1, NULL, NULL),
	('prop_tv_stand_01', 'TV Stand (Trust Poster)', 2200, 3, 'electronic', 1, 1, NULL, NULL),
	('prop_tv_test', 'Test TV (Boxy, Placeholder)', 900, 1, 'electronic', 1, 1, NULL, NULL),
	('prop_t_sofa_02', 'Double Bed (White Frame)', 2100, 3, 'bed', 1, 1, NULL, NULL),
	('prop_ven_market_table1', 'Market Table (Foldable)', 1300, 2, 'table', 1, 1, NULL, NULL),
	('prop_waiting_seat_01', 'Waiting Seat (Brown Leather)', 500, 2, 'chair', 1, 1, NULL, NULL),
	('prop_wall_light_06a', 'Ceiling Light (Glass Dome)', 500, 1, 'light', 1, 1, NULL, NULL),
	('prop_washer_02', 'Washing Machine (Modern)', 2400, 2, 'electronic', 0, 1, NULL, NULL),
	('prop_washer_03', 'Washing Machine (Vintage)', 2000, 2, 'electronic', 0, 1, NULL, NULL),
	('prop_watercooler', 'Water Cooler (Plastic Jug)', 1100, 1, 'kitchen', 1, 1, NULL, NULL),
	('prop_weight_bench_02', 'Weight Bench (Barbell)', 1900, 3, 'recreation', 1, 1, NULL, NULL),
	('prop_weight_rack_02', 'Weight Rack (Dumbbells)', 2400, 3, 'recreation', 1, 1, NULL, NULL),
	('prop_weight_squat', 'Squat Rack (Weights)', 1100, 3, 'recreation', 1, 1, NULL, NULL),
	('prop_w_fountain_01', 'Public Sink (Stainless, Wide)', 180, 1, 'bathroom', 0, 1, NULL, NULL),
	('prop_yacht_table_01', 'Yacht Table (Dark Wicker)', 640, 1, 'table', 1, 1, NULL, NULL),
	('prop_yacht_table_02', 'Yacht Table (Gray Wicker)', 550, 2, 'table', 1, 1, NULL, NULL),
	('prop_yacht_table_03', 'Yacht Table (Black Wicker)', 1000, 3, 'table', 1, 1, NULL, NULL),
	('prop_yaught_chair_01', 'Yacht Chair (Single, Black)', 850, 2, 'chair', 1, 1, NULL, NULL),
	('prop_yaught_sofa_01', 'Yacht Sofa (2-Seat, Black)', 1900, 3, 'sofa', 1, 1, NULL, NULL),
	('p_dinechair_01_s', 'Ornate Wooden Chair (Carved)', 400, 2, 'chair', 1, 1, NULL, NULL),
	('p_lestersbed_s', 'Worn Wooden Bed (Blanket)', 1500, 3, 'bed', 0, 1, NULL, NULL),
	('p_new_j_counter_03', 'Store Counter', 9000, 2, 'storage', 1, 1, 'storage', '{"slots":10,"weight":10000}'),
	('p_v_43_safe_s', 'Vault Safe (Industrial)', 40000, 3, 'storage', 1, 1, 'safe', '{"weight":30000,"slots":12}'),
	('sf_mp_h_yacht_armchair_03', 'Yacht Armchair (White)', 1100, 2, 'chair', 1, 1, NULL, NULL),
	('sf_prop_sf_bed_dog_01a', 'Dog Bed (Grey)', 340, 2, 'decorations', 0, 1, NULL, NULL),
	('sf_prop_sf_bed_dog_01b', 'Dog Bed (Brown)', 330, 2, 'decorations', 0, 1, NULL, NULL),
	('sum_mp_h_yacht_bed_01', 'Yacht Bed (Single, Brown)', 3600, 3, 'bed', 0, 1, NULL, NULL),
	('sum_mp_h_yacht_bed_02', 'Yacht Bed (Double, Gray)', 4000, 3, 'bed', 0, 1, NULL, NULL),
	('v_club_officechair', 'Office Chair (Boss Style)', 950, 2, 'chair', 1, 1, NULL, NULL),
	('v_club_roc_eq1', 'Club Speaker (Wall Mount 1)', 300, 1, 'electronic', 1, 1, NULL, NULL),
	('v_club_roc_eq2', 'Club Speaker (Wall Mount 2)', 450, 1, 'electronic', 1, 1, NULL, NULL),
	('v_club_vu_bear', 'Teddy Bear (Pink, Plush)', 110, 1, 'recreation', 1, 1, NULL, NULL),
	('v_corp_bk_chair3', 'Desk Chair (Gray, No Arms)', 200, 2, 'chair', 1, 1, NULL, NULL),
	('v_corp_cd_chair', 'Desk Chair (Red)', 240, 1, 'chair', 1, 1, NULL, NULL),
	('v_corp_offchair', 'Office Chair (Slim Back)', 800, 2, 'chair', 1, 1, NULL, NULL),
	('v_ilev_liconftable_sml', 'Coffee Table (Modern, Black)', 8000, 3, 'table', 1, 1, NULL, NULL),
	('v_ilev_m_sofa', 'L-Shaped Sofa (Modern)', 4500, 3, 'sofa', 1, 1, NULL, NULL),
	('v_ind_rc_lowtable', 'Wooden Coffee Table (Low)', 800, 1, 'table', 1, 1, NULL, NULL),
	('v_med_fabricchair1', 'Fabric Armchair (Green)', 590, 2, 'chair', 1, 1, NULL, NULL),
	('v_res_cakedome', 'Decorative Cake Dome (Glass)', 75, 1, 'kitchen', 1, 1, NULL, NULL),
	('v_res_d_bed', 'Iron Bed (Red Floral)', 1300, 3, 'bed', 0, 1, NULL, NULL),
	('v_res_fh_bedsideclock', 'Alarm Clock (Black/White)', 100, 1, 'decorations', 0, 1, NULL, NULL),
	('v_res_foodjara', 'Food Jar (Chilli)', 45, 1, 'kitchen', 1, 1, NULL, NULL),
	('v_res_foodjarb', 'Food Jar (Rice)', 40, 1, 'kitchen', 1, 1, NULL, NULL),
	('v_res_fridgemodsml', 'Fridge (Double Door, Water Dispenser)', 9900, 3, 'kitchen', 0, 1, 'storage', '{"weight":8000,"slots":8}'),
	('v_res_mbath', 'Bathtub (Modern Oval)', 600, 3, 'bathroom', 0, 1, NULL, NULL),
	('v_res_mbbed', 'Double Bed (Red Blanket)', 1800, 3, 'bed', 0, 1, NULL, NULL),
	('v_res_mbdresser', 'Dresser (Ornate Wood)', 3100, 3, 'table', 1, 1, NULL, NULL),
	('v_res_mbsink', 'Bathroom Sink (Wall Mount)', 400, 1, 'bathroom', 0, 1, NULL, NULL),
	('v_res_mconsolemod', 'TV Console (Ornate Wood)', 5500, 3, 'storage', 1, 1, 'storage', '{"weight":20000,"slots":15}'),
	('v_res_mdbed', 'Double Bed (Red Blanket)', 2300, 3, 'bed', 0, 1, NULL, NULL),
	('v_res_mflowers', 'Flowers in Vase (White & Pink)', 520, 2, 'plant', 1, 1, NULL, NULL),
	('v_res_mknifeblock', 'Knife Block (Wood)', 110, 1, 'kitchen', 1, 1, NULL, NULL),
	('v_res_mmug', 'Mug (Stoneware)', 20, 1, 'kitchen', 1, 1, NULL, NULL),
	('v_res_monitorsquare', 'Monitor (Square)', 2000, 1, 'electronic', 0, 1, 'device', NULL),
	('v_res_monitorwidelarge', 'Monitor (Wide)', 3000, 1, 'electronic', 0, 1, 'device', NULL),
	('v_res_mousemat', 'Mouse with Mat', 110, 1, 'electronic', 0, 1, NULL, NULL),
	('v_res_mplatesml', 'Dinner Plate (Blue Border)', 20, 1, 'kitchen', 1, 1, NULL, NULL),
	('v_res_msonbed', 'Single Bed (Dark, Unmade)', 1700, 3, 'bed', 0, 1, NULL, NULL),
	('v_res_m_armoire', 'Armoire (Classic, Closed)', 7000, 3, 'storage', 1, 1, 'wardrobe', NULL),
	('v_res_m_armoirmove', 'Armoire (Single, Moveable)', 6200, 3, 'storage', 1, 1, 'wardrobe', NULL),
	('v_res_m_l_chair1', 'Armchair (Vintage, Orange)', 640, 2, 'chair', 1, 1, NULL, NULL),
	('v_res_paperfolders', 'Stack of Folders', 45, 1, 'decorations', 1, 1, NULL, NULL),
	('v_res_pcheadset', 'PC Headset (Lying)', 190, 1, 'electronic', 0, 1, NULL, NULL),
	('v_res_pcspeaker', 'Tower Speaker (Standing)', 300, 1, 'electronic', 0, 1, NULL, NULL),
	('v_res_pctower', 'PC Tower (Black)', 2000, 1, 'electronic', 0, 1, NULL, NULL),
	('v_res_pestle', 'Mortar and Pestle (Stone)', 50, 1, 'kitchen', 1, 1, NULL, NULL),
	('v_res_printer', 'Printer (Multifunction)', 550, 1, 'electronic', 0, 1, NULL, NULL),
	('v_res_r_perfume', 'Perfume Bottle (Green)', 300, 1, 'decorations', 1, 1, NULL, NULL),
	('v_res_tre_bed1', 'Double Bed (White Frame)', 2500, 3, 'bed', 0, 1, NULL, NULL),
	('v_res_tre_bed1_messy', 'Double Bed (Messy Blanket)', 2200, 3, 'bed', 0, 1, NULL, NULL),
	('v_res_tre_bedsidetable', 'Nightstand (Single Drawer)', 5500, 1, 'storage', 1, 1, 'storage', '{"slots":10,"weight":10000}'),
	('v_res_tre_chair', 'Chair (White Wooden)', 400, 1, 'chair', 1, 1, NULL, NULL),
	('v_res_tre_fridge', 'Fridge (Retro)', 7800, 2, 'kitchen', 0, 1, 'storage', '{"weight":8000,"slots":8}'),
	('v_res_tre_lightfan', 'Ceiling Fan (Wooden)', 800, 2, 'light', 1, 1, NULL, NULL),
	('v_res_tt_bed', 'Bed (Simple, Plaid)', 1200, 3, 'bed', 0, 1, NULL, NULL),
	('v_res_tt_bowlpile02', 'Stack of Plates', 40, 1, 'kitchen', 1, 1, NULL, NULL),
	('v_res_vacuum', 'Vacuum Cleaner (Upright)', 1250, 1, 'electronic', 0, 1, NULL, NULL),
	('v_ret_gc_chair03', 'Office Chair (Black Leather)', 800, 2, 'chair', 1, 1, NULL, NULL),
	('v_ret_gc_shred', 'Shredder (Office)', 480, 1, 'electronic', 0, 1, NULL, NULL),
	('v_ret_mirror', 'Wall Mirror (Gold Frame)', 300, 1, 'decorations', 0, 1, NULL, NULL),
	('v_ret_ps_flowers_01', 'Flowers in Vase (Yellow)', 550, 2, 'plant', 1, 1, NULL, NULL),
	('v_ret_ps_flowers_02', 'Flowers in Vase (Pink)', 500, 2, 'plant', 1, 1, NULL, NULL),
	('v_ret_ta_paproll', 'Toilet Paper Roll (Dark Texture)', 15, 1, 'decorations', 1, 1, NULL, NULL),
	('xm_lab_chairarm_03', 'Office Chair (Wood Frame)', 550, 2, 'chair', 1, 1, NULL, NULL),
	('xm_prop_lab_desk_02', 'Modern Desk (Black&Wooden)', 3600, 3, 'table', 1, 1, NULL, NULL),
	('zprop_bin_01a_old', 'Classic Bin (Mesh)', 280, 2, 'outdoor', 1, 0, NULL, NULL);